In [26]:
import os
import sys
import glob
import imghdr
from PIL import Image


In [ ]:


def change_format_image(path, image_original = None, image_result=None):
    """
    path: root directory
    image_original: format of input image
    image_result: format of output image
    """
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    if image_original is None:
        raise Exception ("Input format")
    
    if image_result is None:
        raise Exception ("Output format")
        
    # New Directory  
    directory = "OutputFile/"
    new_path = os.path.join(path, directory)
    
    for root, dirs, files in os.walk(path, topdown=False):
        for name in files:
            
            if imghdr.what(name) == str(image_original).lower():
                if (os.path.splitext(os.path.join(root, name))[0]
                    + image_result):
                    
                    try:
                        # if not exist
                        if not os.path.isdir(new_path):
                            os.mkdir(new_path)
                            
                        original = path + name
                        outfile = os.path.splitext(os.path.join(new_path, name))[0]
                        + '.' + image_result.lower()
                        Image.open(original).convert('RGB').save(outfile)
                    
                    except Exception:
                        raise ("An error has ocurred when trying save the image to new format")
                        

In [ ]:
path = 'C:/Users/virus/source/repos/FER/prueba/'

change_format_image(path, image_original='tiff',image_result='jpg')

In [252]:
def get_folder(string1, string2):
    
    if string1 == string2:
        return None
        
    if  len(string1) < len(string2):
        return string2[len(string1):]
    
    else:
        return string1[len(string2):]

    
    
    
def face_alingment(path):
    
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    
    # New Directory  
    directory = "Outputfile/"
    new_path = os.path.join(path, directory)
    
    # create folder in new_path
    #if not os.path.isdir(new_path):
     #   os.mkdir(new_path)
    

    for root, dirs, files in os.walk(path, topdown=False):
        
        folder = get_folder(root, path)
        if folder is not None:
            
            new_folder = os.path.join(new_path, folder)
            if not os.path.isdir(new_path):
                os.mkdir(new_path)
        
            if not os.path.isdir(new_folder):
                print(new_folder)
                os.mkdir(new_folder)
        #for name in files:
           
         #   original = os.path.join(root+'/', name)
          #  print(original)
            
            
            # create folder in new_path
       #     if not os.path.isdir(new_path):
        #        os.mkdir(new_path)
            
            # save into new directory
         #   new = os.path.join(new_path, name)
          #  print(new)
        
        
        
        
        

            
    
    

In [253]:
set_path = 'C:/Users/virus/source/repos/FER/datasets/CK+48/'

face_alingment(set_path)

C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/anger
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/contempt
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/disgust
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/fear
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/happy
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/sadness
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/surprise


# DATA NORMALIZATION

In [83]:
import numpy as np
from PIL import Image
from numpy import asarray
from scipy import stats

def z_score_norm(image):
    
    
    image = Image.open(image)
    pixels = asarray(image)
    
    mean = np.mean(pixels.flatten(), dtype=np.float64)
    std = np.std(pixels.flatten(), dtype=np.float64)
    print("mean = {}\nstd = {}".format(mean,std))
    #print('dim image: {}'.format(pixels.shape))
    print("\n")
    
    
    return mean, std
    
def read_images(path):
    
    #if not os.path.isdir(path):
    #    raise Exception("Invalid directory")
    directory = "Histogram/"
    new_path = os.path.join(path, directory)
    
    means = []
    stds = []
    
    for root, dirs, files in os.walk(path, topdown=False):

        #if not os.path.isdir(new_path):
         #   os.mkdir(new_path)

        for i, name in enumerate(files, 1):
            original = os.path.join(root, name)
            #print(original)
            mean, std = z_score_norm(original)
            means.append(mean)
            stds.append(std)
            
    mean_gral = np.mean(np.asarray(means))
    std_gral = np.std(np.asarray(stds))
    
    print("mean gral: {}\nstd gral: {}".format(mean_gral, std_gral))
    
    
    
    
if __name__ == '__main__':
    # folder with all images
    dir_image = 'C:/Users/virus/source/repos/DATASETS/CK+/Histogram/'
    # histogram equalization
    read_images(dir_image)

mean = 133.41640625
std = 85.58202289141687


mean = 133.5120695153061
std = 85.77368147286457


mean = 125.18267219387755
std = 75.7217101194935


mean = 125.40717793367347
std = 75.08850955184198


mean = 125.41250637755103
std = 75.0768354581961


mean = 125.41713647959183
std = 75.06685019656082


mean = 126.17533801020409
std = 74.6708978188422


mean = 126.10569196428571
std = 74.68846141554899


mean = 126.11107142857144
std = 74.67317564284203


mean = 126.0962818877551
std = 74.6738483353192


mean = 126.19964923469388
std = 74.64358586369795


mean = 126.11479272959184
std = 74.66599766423509


mean = 126.18257015306122
std = 74.67503815701373


mean = 125.1229719387755
std = 75.73854811963074


mean = 126.16914540816326
std = 74.67577883542853


mean = 126.11777742346939
std = 74.67396687850042


mean = 126.1455644132653
std = 74.65604689792423


mean = 125.99705676020409
std = 74.75838364791312


mean = 126.07735012755101
std = 74.70340326198033


mean = 123.22727997448979


std = 76.78169462542553


mean = 122.85515943877552
std = 76.5997174442462


mean = 122.04760522959184
std = 76.89575715911604


mean = 122.2154368622449
std = 76.83303940014015


mean = 122.22117028061224
std = 76.83713168129063


mean = 122.1886256377551
std = 76.84047144821592


mean = 122.48944834183673
std = 76.70600965194144


mean = 122.44810267857143
std = 76.7202590902971


mean = 122.48504783163266
std = 76.72834347390139


mean = 122.64975446428572
std = 76.62069321304374


mean = 122.76653061224489
std = 76.56405990300341


mean = 128.29889030612244
std = 76.857373381845


mean = 122.53412946428571
std = 76.69170550716704


mean = 122.54195471938776
std = 76.66754574237174


mean = 122.7056568877551
std = 76.5870506944291


mean = 122.70748405612245
std = 76.60237742493486


mean = 122.59931760204081
std = 76.69945488487107


mean = 122.5778730867347
std = 76.7121953746647


mean = 122.52606505102041
std = 76.71044360856818


mean = 122.72194196428572
std = 76.6491204632179

mean = 126.61401466836735
std = 75.21682686754835


mean = 126.66286352040817
std = 75.16811035778028


mean = 126.94596301020408
std = 75.90003836379915


mean = 133.4472193877551
std = 85.54454402635132


mean = 133.68837053571428
std = 85.40694240624781


mean = 126.96577487244897
std = 75.92455295402269


mean = 126.92719706632653
std = 75.92775711909255


mean = 126.91511160714286
std = 75.92669832024042


mean = 126.88355229591836
std = 75.90420174794961


mean = 126.9034980867347
std = 75.89205891518452


mean = 126.87772959183674
std = 75.76158932661211


mean = 126.91312818877552
std = 75.74087501345439


mean = 126.88636479591837
std = 75.76918643189062


mean = 126.92377232142857
std = 75.7162492328228


mean = 126.91062181122449
std = 75.72997621742273


mean = 133.46900510204082
std = 85.51166073831372


mean = 126.93939732142857
std = 75.70730774040273


mean = 126.94392538265306
std = 75.67093315224933


mean = 126.92545599489796
std = 75.69196049700443


mean = 126.9576

mean = 126.30103635204081
std = 75.47937082305565


mean = 126.51323979591837
std = 75.32498037899218


mean = 126.46327806122449
std = 75.31500038423133


mean = 126.48002232142858
std = 75.30972739921039


mean = 126.49476084183674
std = 75.30398436893586


mean = 126.33327487244898
std = 75.40231721407673


mean = 126.34734056122448
std = 75.43605291254524


mean = 126.3269706632653
std = 75.42646323069567


mean = 126.26039540816326
std = 75.4650514233128


mean = 126.3551881377551
std = 75.46491180312296


mean = 133.74870854591836
std = 85.3908508602697


mean = 126.31764349489796
std = 75.40266764642271


mean = 126.36712053571429
std = 75.39104342365314


mean = 126.28023596938776
std = 75.39815535755413


mean = 126.39076211734694
std = 75.4080287705121


mean = 126.34551339285714
std = 75.38580183683193


mean = 126.34167091836734
std = 75.37358039759641


mean = 126.1593463010204
std = 75.42428251271187


mean = 126.31792091836735
std = 75.26495828353535


mean = 126.3439604

mean = 127.58479591836735
std = 76.73482867708253


mean = 133.4340911989796
std = 85.52957988983688


mean = 131.1853762755102
std = 86.97907463236078


mean = 127.73900829081633
std = 76.7203851162379


mean = 127.69948022959184
std = 76.64786170410412


mean = 127.71354910714285
std = 76.70466874971386


mean = 127.58836734693878
std = 76.77420501710137


mean = 127.78406568877551
std = 76.62182386333312


mean = 127.71086415816326
std = 76.6480683678401


mean = 127.5628730867347
std = 76.73228665191796


mean = 127.58632653061224
std = 76.81339644219108


mean = 127.73331951530612
std = 76.69633906207119


mean = 127.71470982142857
std = 76.65733555795975


mean = 131.49934948979592
std = 86.55088485520928


mean = 127.60558035714286
std = 76.80537618354816


mean = 127.65582908163265
std = 76.83443290310807


mean = 127.67992028061225
std = 76.67663656896643


mean = 127.74613201530612
std = 76.67627337464229


mean = 127.74954719387755
std = 76.68120431253331


mean = 127.646192

mean = 125.9340625
std = 74.84401808128834


mean = 125.86918048469387
std = 74.89583817321014


mean = 125.88001913265306
std = 74.86131326134961


mean = 125.86587053571428
std = 74.90114107721901


mean = 125.89766900510205
std = 74.89557881950923


mean = 125.92690369897959
std = 74.84609245329855


mean = 126.0030612244898
std = 74.8393486267338


mean = 131.76511160714287
std = 86.5116932214949


mean = 125.90994897959183
std = 74.8517838815649


mean = 125.95938775510204
std = 74.8290970065043


mean = 125.85152104591836
std = 74.89261230660429


mean = 125.82639349489796
std = 74.90320674411606


mean = 125.92888711734693
std = 74.86942517642791


mean = 125.9210299744898
std = 74.86760370497967


mean = 125.97111607142857
std = 74.82838734195907


mean = 125.96420599489795
std = 74.8323103068155


mean = 125.92633609693877
std = 74.82728649268913


mean = 125.87740752551021
std = 74.86755793166706


mean = 131.6403794642857
std = 86.48448033172694


mean = 125.99658482142857
s

mean = 126.02361607142858
std = 74.96377503355316


mean = 126.01992028061224
std = 74.93960154237799


mean = 126.01069196428571
std = 74.97557751064241


mean = 126.10039221938776
std = 74.90024719039917


mean = 126.09371173469388
std = 74.94273468550098


mean = 126.11220344387755
std = 74.87208264259264


mean = 125.33148278061225
std = 75.38269997329027


mean = 126.00997130102041
std = 74.97482208801351


mean = 133.66798469387754
std = 85.71821238338937


mean = 124.57885204081633
std = 76.03439814138734


mean = 125.99292729591836
std = 74.95121479476867


mean = 126.0332174744898
std = 74.95021079017887


mean = 126.07203125
std = 74.94294870674138


mean = 125.98523278061225
std = 74.96845217895194


mean = 126.02355867346938
std = 74.96380708238358


mean = 126.04891262755102
std = 74.94104006312992


mean = 125.96407206632654
std = 74.97500693683516


mean = 126.0206568877551
std = 74.95885934098219


mean = 126.03938775510204
std = 74.92516201308062


mean = 126.098753188

mean = 124.59774872448979
std = 75.38095573338599


mean = 124.72144451530612
std = 75.37728568355669


mean = 125.3431887755102
std = 75.6656512148034


mean = 124.56563456632654
std = 75.43162502789265


mean = 124.63515943877552
std = 75.38127011208968


mean = 124.8280612244898
std = 75.2600876997754


mean = 124.75095982142857
std = 75.30994373278588


mean = 123.64619897959183
std = 75.90514461599221


mean = 124.71799744897959
std = 75.35223894043712


mean = 124.65847895408163
std = 75.36681855948449


mean = 124.56982780612245
std = 75.40768660642358


mean = 124.60238201530612
std = 75.40514540050911


mean = 124.44280293367346
std = 75.4549638041082


mean = 124.95051339285715
std = 75.81723448752214


mean = 124.72910076530613
std = 75.33320625308568


mean = 124.64686224489796
std = 75.44129801051699


mean = 124.56213010204081
std = 75.41572632817059


mean = 124.54561224489795
std = 75.47331341703214


mean = 124.63751275510204
std = 75.37981111959525


mean = 124.541256

In [14]:


#mean gral: 117.9951938948301
#std gral: 9.114636153038024




#mean gral: 113.84889976249121
#std gral: 8.53443628163184



# histogram
# 126.28778215950788
# 2.6452071285228773

In [102]:
  
def zscore(origin, final):
    
    image = Image.open(origin)
    pixels = asarray(image)

    print(pixels)
    print('dim image: {}'.format(pixels.shape))
    print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))

    pixels = (pixels - 126.28778215950788) /  2.6452071285228773#- 113.84889976249121

    #pixels = pixels / 2.6452071285228773 #/ 8.53443
    print("\n\n")
    print(pixels)
    im = Image.fromarray(np.float64(pixels))

    im.convert('L').save(final)



In [103]:

origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/79.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/79_zscore.png'

zscore(origin, final)

[[117 209 224 ...   0   0   0]
 [ 72 202 224 ...   0   0   0]
 [  0   4   9 ...   0   0   0]
 ...
 [ 48  48  47 ... 233 238 245]
 [ 43  44  46 ... 226 237 243]
 [  0   0   4 ...   0   0  12]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[ -3.51117387  31.26871123  36.93934467 ... -47.74211471 -47.74211471
  -47.74211471]
 [-20.52307419  28.62241562  36.93934467 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -46.22994579 -44.33973464 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-29.5960877  -29.5960877  -29.97412993 ...  40.34172473  42.23193588
   44.87823149]
 [-31.48629885 -31.10825662 -30.35217216 ...  37.69542913  41.85389365
   44.12214703]
 [-47.74211471 -47.74211471 -46.22994579 ... -47.74211471 -47.74211471
  -43.20560796]]


In [104]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/80.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/80_zscore.png'

zscore(origin, final)

[[ 57 193 212 ...   0   0   4]
 [ 68 204 226 ...   0   0   4]
 [  0   0   0 ...   0   0   0]
 ...
 [ 52  52  52 ... 233 239 255]
 [ 48  48  48 ... 226 236 241]
 [  4   4   4 ...   0   0  13]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-26.19370764  25.22003556  32.40283792 ... -47.74211471 -47.74211471
  -46.22994579]
 [-22.03524311  29.37850008  37.69542913 ... -47.74211471 -47.74211471
  -46.22994579]
 [-47.74211471 -47.74211471 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-28.08391878 -28.08391878 -28.08391878 ...  40.34172473  42.60997811
   48.65865378]
 [-29.5960877  -29.5960877  -29.5960877  ...  37.69542913  41.47585142
   43.36606257]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -47.74211471
  -42.82756573]]


In [105]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/81.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/81_zscore.png'

zscore(origin, final)

[[ 71 204 225 ...   0   0   0]
 [ 91 204 221 ...   0   0   0]
 [  0  16   0 ...   0   0   0]
 ...
 [ 52  51  50 ... 233 238 255]
 [ 50  50  50 ... 235 239 241]
 [  4   4   4 ...   0   0   4]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-20.90111642  29.37850008  37.3173869  ... -47.74211471 -47.74211471
  -47.74211471]
 [-13.34027184  29.37850008  35.80521798 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -41.69343904 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-28.08391878 -28.46196101 -28.84000324 ...  40.34172473  42.23193588
   48.65865378]
 [-28.84000324 -28.84000324 -28.84000324 ...  41.09780919  42.60997811
   43.36606257]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -47.74211471
  -46.22994579]]


In [106]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/82.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/82_zscore.png'

zscore(origin, final)

[[ 53 178 215 ...   0   0   0]
 [ 47 154 216 ...   0   0   0]
 [  9   9   0 ...   0   0   0]
 ...
 [ 47  48  49 ... 234 239 255]
 [ 45  46  46 ... 234 239 255]
 [  4   4   4 ...   0   0   4]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-27.70587655  19.54940212  33.5369646  ... -47.74211471 -47.74211471
  -47.74211471]
 [-29.97412993  10.47638861  33.91500683 ... -47.74211471 -47.74211471
  -47.74211471]
 [-44.33973464 -44.33973464 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-29.97412993 -29.5960877  -29.21804547 ...  40.71976696  42.60997811
   48.65865378]
 [-30.73021439 -30.35217216 -30.35217216 ...  40.71976696  42.60997811
   48.65865378]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -47.74211471
  -46.22994579]]


In [107]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/83.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/83_zscore.png'

zscore(origin, final)

[[ 55 195 217 ...   0   0   0]
 [ 57 190 213 ...   0   0   0]
 [  7  16   0 ...   0   0   0]
 ...
 [ 53  52  51 ... 237 240 255]
 [ 50  50  50 ... 234 239 255]
 [  0   0   0 ...   0   0   0]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-26.94979209  25.97612002  34.29304906 ... -47.74211471 -47.74211471
  -47.74211471]
 [-26.19370764  24.08590887  32.78088015 ... -47.74211471 -47.74211471
  -47.74211471]
 [-45.0958191  -41.69343904 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-27.70587655 -28.08391878 -28.46196101 ...  41.85389365  42.98802034
   48.65865378]
 [-28.84000324 -28.84000324 -28.84000324 ...  40.71976696  42.60997811
   48.65865378]
 [-47.74211471 -47.74211471 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]]


In [108]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/84.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/84_zscore.png'

zscore(origin, final)

[[ 58 198 220 ...   0   0   0]
 [ 66 200 222 ...   0   0   0]
 [  0   4   0 ...   0   0   0]
 ...
 [ 46  47  47 ... 236 243 255]
 [ 50  50  50 ... 235 240 255]
 [  4   4   4 ...   0   4   7]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-25.81566541  27.11024671  35.42717575 ... -47.74211471 -47.74211471
  -47.74211471]
 [-22.79132757  27.86633116  36.18326021 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -46.22994579 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-30.35217216 -29.97412993 -29.97412993 ...  41.47585142  44.12214703
   48.65865378]
 [-28.84000324 -28.84000324 -28.84000324 ...  41.09780919  42.98802034
   48.65865378]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -46.22994579
  -45.0958191 ]]
