In [1]:
import os
import sys
import glob
import imghdr
from PIL import Image


In [ ]:


def change_format_image(path, image_original = None, image_result=None):
    """
    path: root directory
    image_original: format of input image
    image_result: format of output image
    """
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    if image_original is None:
        raise Exception ("Input format")
    
    if image_result is None:
        raise Exception ("Output format")
        
    # New Directory  
    directory = "OutputFile/"
    new_path = os.path.join(path, directory)
    
    for root, dirs, files in os.walk(path, topdown=False):
        for name in files:
            
            if imghdr.what(name) == str(image_original).lower():
                if (os.path.splitext(os.path.join(root, name))[0]
                    + image_result):
                    
                    try:
                        # if not exist
                        if not os.path.isdir(new_path):
                            os.mkdir(new_path)
                            
                        original = path + name
                        outfile = os.path.splitext(os.path.join(new_path, name))[0]
                        + '.' + image_result.lower()
                        Image.open(original).convert('RGB').save(outfile)
                    
                    except Exception:
                        raise ("An error has ocurred when trying save the image to new format")
                        

In [ ]:
path = 'C:/Users/virus/source/repos/FER/prueba/'

change_format_image(path, image_original='tiff',image_result='jpg')

In [252]:
def get_folder(string1, string2):
    
    if string1 == string2:
        return None
        
    if  len(string1) < len(string2):
        return string2[len(string1):]
    
    else:
        return string1[len(string2):]

    
    
    
def face_alingment(path):
    
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    
    # New Directory  
    directory = "Outputfile/"
    new_path = os.path.join(path, directory)
    
    # create folder in new_path
    #if not os.path.isdir(new_path):
     #   os.mkdir(new_path)
    

    for root, dirs, files in os.walk(path, topdown=False):
        
        folder = get_folder(root, path)
        if folder is not None:
            
            new_folder = os.path.join(new_path, folder)
            if not os.path.isdir(new_path):
                os.mkdir(new_path)
        
            if not os.path.isdir(new_folder):
                print(new_folder)
                os.mkdir(new_folder)
        #for name in files:
           
         #   original = os.path.join(root+'/', name)
          #  print(original)
            
            
            # create folder in new_path
       #     if not os.path.isdir(new_path):
        #        os.mkdir(new_path)
            
            # save into new directory
         #   new = os.path.join(new_path, name)
          #  print(new)
        
        
        
        
        

            
    
    

In [253]:
set_path = 'C:/Users/virus/source/repos/FER/datasets/CK+48/'

face_alingment(set_path)

C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/anger
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/contempt
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/disgust
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/fear
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/happy
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/sadness
C:/Users/virus/source/repos/FER/datasets/CK+48/Outputfile/surprise


# DATA NORMALIZATION | z-score

In [88]:
import numpy as np
from PIL import Image
from numpy import asarray
from scipy import stats

def mean_std_by(image):
    
    image = Image.open(image)
    pixels = asarray(image)
    
    mean = np.mean(pixels.flatten(), dtype=np.float64)
    std = np.std(pixels.flatten(), dtype=np.float64)
    
    return mean, std
    
def read_images(path):

    if not os.path.isdir(path):
        raise Exception("Invalid directory...")
        
    
    directory = "Histogram/"
    new_path = os.path.join(path, directory)
    
    means = []
    stds = []
    
    for root, dirs, files in os.walk(path, topdown=False):

        for i, name in enumerate(files, 1):
            original = os.path.join(root, name)

            mean, std = mean_std_by(original)
            means.append(mean)
            stds.append(std)
            if i % 100 == 0:
                print("computing std, mean...left {}".format(len(files) - i))
            
    mean_gral = np.mean(np.asarray(means))
    std_gral = np.std(np.asarray(stds))
    
    return mean_gral, std_gral
    
    
    
def zscore(origin, final, mean, std):
    
    image = Image.open(origin)
    pixels = asarray(image)

    pixels = (pixels - mean) /  std
    
    im = Image.fromarray(np.float64(pixels))

    im.convert('L').save(final)
    
    
def zscore_normalization(path):
    
    
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    
    # New Directory  
    directory = "ZscoreOutput/"
    new_path = os.path.join(path, directory)
    
    if not os.path.isdir(new_path):
        os.mkdir(new_path)
    
    # compute mean and std for all images
    mean, std = read_images(path)
    print("")
    print("mean gral: {}\nstd gral: {}".format(mean, std))
    print("")
    
    for root, dirs, files in os.walk(path, topdown=False):

        for i, file in enumerate(files):
            original = os.path.join(root, file)
            
            new_folder = os.path.join(new_path, file)
            
            zscore(original, new_folder, mean, std)
            if i%100 == 0:
                print("z score nomalization, left...{}".format(len(files) - i))

    print("finished...")
    
if __name__ == '__main__':
    # folder with all images
    dir_image = 'C:/Users/virus/source/repos/DATASETS/CK+/Histogram/'
    
    # apply zscore normalization after histogram equalization was applied
    zscore_normalization(dir_image)
    
    
    
    
    
    

computing std, mean...left 1118
computing std, mean...left 1018
computing std, mean...left 918
computing std, mean...left 818
computing std, mean...left 718
computing std, mean...left 618
computing std, mean...left 518
computing std, mean...left 418
computing std, mean...left 318
computing std, mean...left 218
computing std, mean...left 118
computing std, mean...left 18

mean gral: 126.28778215950788
std gral: 2.6452071285228773

z score nomalization, left...1218
z score nomalization, left...1118
z score nomalization, left...1018
z score nomalization, left...918
z score nomalization, left...818
z score nomalization, left...718
z score nomalization, left...618
z score nomalization, left...518
z score nomalization, left...418
z score nomalization, left...318
z score nomalization, left...218
z score nomalization, left...118
z score nomalization, left...18
finished...


In [28]:


#mean gral: 117.9951938948301
#std gral: 9.114636153038024




#mean gral: 113.84889976249121
#std gral: 8.53443628163184



# histogram
# 126.28778215950788
# 2.6452071285228773

In [15]:
  
def zscore(origin, final):
    
    image = Image.open(origin)
    pixels = asarray(image)

    print(pixels)
    print('dim image: {}'.format(pixels.shape))
    print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))

    pixels = (pixels - 126.28778215950788) /  2.6452071285228773#- 113.84889976249121

    #pixels = pixels / 2.6452071285228773 #/ 8.53443
    print("\n\n")
    print(pixels)
    im = Image.fromarray(np.float64(pixels))

    im.convert('L').save(final)



In [17]:

origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/79.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/79_zscore.png'

zscore(origin, final)

[[117 209 224 ...   0   0   0]
 [ 72 202 224 ...   0   0   0]
 [  0   4   9 ...   0   0   0]
 ...
 [ 48  48  47 ... 233 238 245]
 [ 43  44  46 ... 226 237 243]
 [  0   0   4 ...   0   0  12]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[ -3.51117387  31.26871123  36.93934467 ... -47.74211471 -47.74211471
  -47.74211471]
 [-20.52307419  28.62241562  36.93934467 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -46.22994579 -44.33973464 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-29.5960877  -29.5960877  -29.97412993 ...  40.34172473  42.23193588
   44.87823149]
 [-31.48629885 -31.10825662 -30.35217216 ...  37.69542913  41.85389365
   44.12214703]
 [-47.74211471 -47.74211471 -46.22994579 ... -47.74211471 -47.74211471
  -43.20560796]]


In [104]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/80.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/80_zscore.png'

zscore(origin, final)

[[ 57 193 212 ...   0   0   4]
 [ 68 204 226 ...   0   0   4]
 [  0   0   0 ...   0   0   0]
 ...
 [ 52  52  52 ... 233 239 255]
 [ 48  48  48 ... 226 236 241]
 [  4   4   4 ...   0   0  13]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-26.19370764  25.22003556  32.40283792 ... -47.74211471 -47.74211471
  -46.22994579]
 [-22.03524311  29.37850008  37.69542913 ... -47.74211471 -47.74211471
  -46.22994579]
 [-47.74211471 -47.74211471 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-28.08391878 -28.08391878 -28.08391878 ...  40.34172473  42.60997811
   48.65865378]
 [-29.5960877  -29.5960877  -29.5960877  ...  37.69542913  41.47585142
   43.36606257]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -47.74211471
  -42.82756573]]


In [105]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/81.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/81_zscore.png'

zscore(origin, final)

[[ 71 204 225 ...   0   0   0]
 [ 91 204 221 ...   0   0   0]
 [  0  16   0 ...   0   0   0]
 ...
 [ 52  51  50 ... 233 238 255]
 [ 50  50  50 ... 235 239 241]
 [  4   4   4 ...   0   0   4]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-20.90111642  29.37850008  37.3173869  ... -47.74211471 -47.74211471
  -47.74211471]
 [-13.34027184  29.37850008  35.80521798 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -41.69343904 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-28.08391878 -28.46196101 -28.84000324 ...  40.34172473  42.23193588
   48.65865378]
 [-28.84000324 -28.84000324 -28.84000324 ...  41.09780919  42.60997811
   43.36606257]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -47.74211471
  -46.22994579]]


In [106]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/82.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/82_zscore.png'

zscore(origin, final)

[[ 53 178 215 ...   0   0   0]
 [ 47 154 216 ...   0   0   0]
 [  9   9   0 ...   0   0   0]
 ...
 [ 47  48  49 ... 234 239 255]
 [ 45  46  46 ... 234 239 255]
 [  4   4   4 ...   0   0   4]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-27.70587655  19.54940212  33.5369646  ... -47.74211471 -47.74211471
  -47.74211471]
 [-29.97412993  10.47638861  33.91500683 ... -47.74211471 -47.74211471
  -47.74211471]
 [-44.33973464 -44.33973464 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-29.97412993 -29.5960877  -29.21804547 ...  40.71976696  42.60997811
   48.65865378]
 [-30.73021439 -30.35217216 -30.35217216 ...  40.71976696  42.60997811
   48.65865378]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -47.74211471
  -46.22994579]]


In [107]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/83.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/83_zscore.png'

zscore(origin, final)

[[ 55 195 217 ...   0   0   0]
 [ 57 190 213 ...   0   0   0]
 [  7  16   0 ...   0   0   0]
 ...
 [ 53  52  51 ... 237 240 255]
 [ 50  50  50 ... 234 239 255]
 [  0   0   0 ...   0   0   0]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-26.94979209  25.97612002  34.29304906 ... -47.74211471 -47.74211471
  -47.74211471]
 [-26.19370764  24.08590887  32.78088015 ... -47.74211471 -47.74211471
  -47.74211471]
 [-45.0958191  -41.69343904 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-27.70587655 -28.08391878 -28.46196101 ...  41.85389365  42.98802034
   48.65865378]
 [-28.84000324 -28.84000324 -28.84000324 ...  40.71976696  42.60997811
   48.65865378]
 [-47.74211471 -47.74211471 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]]


In [108]:
origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/84.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/84_zscore.png'

zscore(origin, final)

[[ 58 198 220 ...   0   0   0]
 [ 66 200 222 ...   0   0   0]
 [  0   4   0 ...   0   0   0]
 ...
 [ 46  47  47 ... 236 243 255]
 [ 50  50  50 ... 235 240 255]
 [  4   4   4 ...   0   4   7]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[-25.81566541  27.11024671  35.42717575 ... -47.74211471 -47.74211471
  -47.74211471]
 [-22.79132757  27.86633116  36.18326021 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -46.22994579 -47.74211471 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-30.35217216 -29.97412993 -29.97412993 ...  41.47585142  44.12214703
   48.65865378]
 [-28.84000324 -28.84000324 -28.84000324 ...  41.09780919  42.98802034
   48.65865378]
 [-46.22994579 -46.22994579 -46.22994579 ... -47.74211471 -46.22994579
  -45.0958191 ]]


In [43]:
matrix = [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]

matrix = np.asarray(matrix)

matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
points = [(199, 235), # 36
          (209, 229), # 37
          (221, 228), # 38
          (234, 235), # 39
          (222, 238), # 40
          (209, 239), # 41
          (281, 232), # 42
          (292, 224), # 43
          (305, 223), # 44
          (316, 228), # 45
          (306, 233), # 46
          (294, 234)] # 47


#           (x , y)
left = [  (199, 235), # 36
          (209, 229), # 37
          (221, 228), # 38
          (234, 235), # 39
          (222, 238), # 40
          (209, 239)] # 41

#           (x , y)
right = [ (281, 232), # 42
          (292, 224), # 43
          (305, 223), # 44
          (316, 228), # 45
          (306, 233), # 46
          (294, 234)] # 47

In [135]:
val = np.asarray(right)
val[:,0]

array([281, 292, 305, 316, 306, 294])

In [136]:
np.sum(val[:,0])

1794

In [141]:
import math 


def compute_angle(left, right):
    
    # as array, much more fast
    aux_left = np.asarray(left)  
    aux_right = np.asarray(right)
    
    # compute numerator
    asum_x = np.sum(aux_right[:,1]) # point 42 to 47 => 'y'
    asum_y = np.sum(aux_left[:,1])  # point 36 to 41 => 'y'
    
    numerador_aux = asum_x - asum_y
    
    # compute denominator
    asum2_x = np.sum(aux_right[:,0]) # point 42 to 47 => 'x'
    asum2_y = np.sum(aux_left[:,0])  # point 36 to 41 => 'x'
    
    denominador_aux = asum2_x - asum2_y
    
    # compute angle=arctan(x)
    angle2 = np.arctan(numerador_aux / denominador_aux)
    
    ########################################
    ########################################
    ########################################
    #sum_x = sum([cord[1] for cord in right])
    #sum_y = sum([cord[1] for cord in left])
    
    #numerador = sum_x - sum_y
    
    #sum2_x = sum([cord[0] for cord in right])
    #sum2_y = sum([cord[0] for cord in left])
    
    #denominador = sum2_x - sum2_y
    
    #angle = math.atan(numerador / denominador)
    
    print("angle2 = {}".format(angle2))



compute_angle(left, right)

angle2 = -0.05992815512120788


In [143]:
from PIL import Image, ImageDraw


im = Image.open("C:/Users/virus/source/repos/DATASETS/PRUEBA/landmarck/rotate1.png").convert('RGB')
draw = ImageDraw.Draw(im)

draw.point(points, fill='red')

im.show()