In [1]:
import os
import sys
import glob
import imghdr
from PIL import Image


In [2]:


def change_format_image(path, image_original = None, image_result=None):
    """
    path: root directory
    image_original: format of input image
    image_result: format of output image
    """
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    if image_original is None:
        raise Exception ("Input format")
    
    if image_result is None:
        raise Exception ("Output format")
        
    # New Directory  
    directory = "OutputFile/"
    new_path = os.path.join(path, directory)
    
    for root, dirs, files in os.walk(path, topdown=False):
        for name in files:
            
            if imghdr.what(name) == str(image_original).lower():
                if (os.path.splitext(os.path.join(root, name))[0]
                    + image_result):
                    
                    try:
                        # if not exist
                        if not os.path.isdir(new_path):
                            os.mkdir(new_path)
                            
                        original = path + name
                        outfile = os.path.splitext(os.path.join(new_path, name))[0]
                        + '.' + image_result.lower()
                        Image.open(original).convert('RGB').save(outfile)
                    
                    except Exception:
                        raise ("An error has ocurred when trying save the image to new format")
                        

In [3]:
path = 'C:/Users/virus/source/repos/FER/prueba/'

######change_format_image(path, image_original='tiff',image_result='jpg')

In [4]:
def get_folder(string1, string2):
    
    if string1 == string2:
        return None
        
    if  len(string1) < len(string2):
        return string2[len(string1):]
    
    else:
        return string1[len(string2):]

    
    
    
def face_alingment(path):
    
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    
    # New Directory  
    directory = "Outputfile/"
    new_path = os.path.join(path, directory)
    
    # create folder in new_path
    #if not os.path.isdir(new_path):
     #   os.mkdir(new_path)
    

    for root, dirs, files in os.walk(path, topdown=False):
        
        folder = get_folder(root, path)
        if folder is not None:
            
            new_folder = os.path.join(new_path, folder)
            if not os.path.isdir(new_path):
                os.mkdir(new_path)
        
            if not os.path.isdir(new_folder):
                print(new_folder)
                os.mkdir(new_folder)
        #for name in files:
           
         #   original = os.path.join(root+'/', name)
          #  print(original)
            
            
            # create folder in new_path
       #     if not os.path.isdir(new_path):
        #        os.mkdir(new_path)
            
            # save into new directory
         #   new = os.path.join(new_path, name)
          #  print(new)
        
        
        
        
        

            
    
    

In [5]:
set_path = 'C:/Users/virus/source/repos/FER/datasets/CK+48/'

##########face_alingment(set_path)

# DATA NORMALIZATION | z-score

In [6]:
import numpy as np
from PIL import Image
from numpy import asarray
from scipy import stats

def mean_std_by(image):
    
    image = Image.open(image)
    pixels = asarray(image)
    
    mean = np.mean(pixels.flatten(), dtype=np.float64)
    std = np.std(pixels.flatten(), dtype=np.float64)
    
    return mean, std
    
def read_images(path):

    if not os.path.isdir(path):
        raise Exception("Invalid directory...")
        
    
    directory = "Histogram/"
    new_path = os.path.join(path, directory)
    
    means = []
    stds = []
    
    for root, dirs, files in os.walk(path, topdown=False):

        for i, name in enumerate(files, 1):
            original = os.path.join(root, name)

            mean, std = mean_std_by(original)
            means.append(mean)
            stds.append(std)
            if i % 100 == 0:
                print("computing std, mean...left {}".format(len(files) - i))
            
    mean_gral = np.mean(np.asarray(means))
    std_gral = np.std(np.asarray(stds))
    
    return mean_gral, std_gral
    
    
    
def zscore(origin, final, mean, std):
    
    image = Image.open(origin)
    pixels = asarray(image)

    pixels = (pixels - mean) /  std
    
    im = Image.fromarray(np.float64(pixels))

    im.convert('L').save(final)
    
    
def zscore_normalization(path):
    
    
    if not os.path.isdir(path):
        raise Exception("Invalid directory")
    
    
    # New Directory  
    directory = "ZscoreOutput/"
    new_path = os.path.join(path, directory)
    
    if not os.path.isdir(new_path):
        os.mkdir(new_path)
    
    # compute mean and std for all images
    mean, std = read_images(path)
    print("")
    print("mean gral: {}\nstd gral: {}".format(mean, std))
    print("")
    
    for root, dirs, files in os.walk(path, topdown=False):

        for i, file in enumerate(files):
            original = os.path.join(root, file)
            
            new_folder = os.path.join(new_path, file)
            
            zscore(original, new_folder, mean, std)
            if i%100 == 0:
                print("z score nomalization, left...{}".format(len(files) - i))

    print("finished...")
    
if __name__ == '__main__':
    # folder with all images
    dir_image = 'C:/Users/virus/source/repos/DATASETS/CK+/Histogram/'
    
    # apply zscore normalization after histogram equalization was applied
    ###############zscore_normalization(dir_image)
    
    
    
    
    
    

In [28]:


#mean gral: 117.9951938948301
#std gral: 9.114636153038024




#mean gral: 113.84889976249121
#std gral: 8.53443628163184



# histogram
# 126.28778215950788
# 2.6452071285228773

In [15]:
  
def zscore(origin, final):
    
    image = Image.open(origin)
    pixels = asarray(image)

    print(pixels)
    print('dim image: {}'.format(pixels.shape))
    print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))

    pixels = (pixels - 126.28778215950788) /  2.6452071285228773#- 113.84889976249121

    #pixels = pixels / 2.6452071285228773 #/ 8.53443
    print("\n\n")
    print(pixels)
    im = Image.fromarray(np.float64(pixels))

    im.convert('L').save(final)



In [17]:

origin = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/79.png'
final = 'C:/Users/virus/source/repos/DATASETS/PRUEBA/79_zscore.png'

zscore(origin, final)

[[117 209 224 ...   0   0   0]
 [ 72 202 224 ...   0   0   0]
 [  0   4   9 ...   0   0   0]
 ...
 [ 48  48  47 ... 233 238 245]
 [ 43  44  46 ... 226 237 243]
 [  0   0   4 ...   0   0  12]]
dim image: (490, 640)
Min: 0.000, Max: 255.000



[[ -3.51117387  31.26871123  36.93934467 ... -47.74211471 -47.74211471
  -47.74211471]
 [-20.52307419  28.62241562  36.93934467 ... -47.74211471 -47.74211471
  -47.74211471]
 [-47.74211471 -46.22994579 -44.33973464 ... -47.74211471 -47.74211471
  -47.74211471]
 ...
 [-29.5960877  -29.5960877  -29.97412993 ...  40.34172473  42.23193588
   44.87823149]
 [-31.48629885 -31.10825662 -30.35217216 ...  37.69542913  41.85389365
   44.12214703]
 [-47.74211471 -47.74211471 -46.22994579 ... -47.74211471 -47.74211471
  -43.20560796]]


In [60]:
points_68 = [(163, 232),
             (168, 258),
             (175, 282),
             (182, 307),
             (191, 329),
             (205, 349),
             (223, 366),
             (244, 379),
             (269, 383),
             (293, 377),
             (315, 364),
             (336, 346),
             (351, 323),
             (358, 298),
             (361, 271),
             (363, 244),
             (362, 217),
             (176, 217),
             (184, 201),
             (201, 195),
             (219, 195),
             (235, 203),
             (268, 203),
             (285, 194),
             (304, 190),
             (324, 194),
             (337, 208),
             (253, 226),
             (255, 244),
             (255, 262),
             (257, 280),
             (241, 292),
             (250, 296),
             (259, 298),
             (269, 295),
             (278, 290),
             (199, 235),
             (209, 229),
             (221, 228),
             (234, 235),
             (222, 238),
             (209, 239),
             (281, 232),
             (292, 224),
             (305, 223),
             (316, 228),
             (306, 233),
             (294, 234),
             (231, 319),
             (243, 317),
             (254, 315),
             (262, 317),
             (271, 314),
             (284, 315),
             (299, 315),
             (285, 330),
             (274, 336),
             (265, 337),
             (256, 335),
             (244, 330),
             (237, 320),
             (254, 321),
             (263, 322),
             (272, 321),
             (293, 318),
             (272, 323),
             (263, 325),
             (255, 323)]

points = [(199, 235), # 36
          (209, 229), # 37
          (221, 228), # 38
          (234, 235), # 39
          (222, 238), # 40
          (209, 239), # 41
          (281, 232), # 42
          (292, 224), # 43
          (305, 223), # 44
          (316, 228), # 45
          (306, 233), # 46
          (294, 234)] # 47


#           (x , y)
left = [  (199, 235), # 36
          (209, 229), # 37
          (221, 228), # 38
          (234, 235), # 39
          (222, 238), # 40
          (209, 239)] # 41

#           (x , y)
right = [ (281, 232), # 42
          (292, 224), # 43
          (305, 223), # 44
          (316, 228), # 45
          (306, 233), # 46
          (294, 234)] # 47

In [61]:
val = np.asarray(points)
x = val[0:6]
y = val[6:]

In [62]:
x

array([[199, 235],
       [209, 229],
       [221, 228],
       [234, 235],
       [222, 238],
       [209, 239]])

In [63]:
y

array([[281, 232],
       [292, 224],
       [305, 223],
       [316, 228],
       [306, 233],
       [294, 234]])

In [84]:
np.sum(y[:,1])

1374

In [72]:
import math 


def compute_distance(points):
    
    # as array, much more fast
    points = np.asarray(points)
    
    # select eye right and left
    left = points[0:6] # points(x,y), 36 to 41
    right = points[6:] # points(x,y), 42 to 47
    
    sum_x = np.sum(right[:,0])
    sum_y = np.sum(left[:,0])
    
    d = (sum_x - sum_y) / 6
    return d
    


def compute_angle(points):
    
    # as array, much more fast
    points = np.asarray(points)
    
    # select eye right and left
    left = points[0:6] # points 36 to 41
    right = points[6:] # points 42 to 47
    
    # compute numerator
    asum_x = np.sum(right[:,1]) # points 42 to 47 => 'y'
    asum_y = np.sum(left[:,1])  # points 36 to 41 => 'y'
    
    numerador = asum_x - asum_y
    
    # compute denominator
    asum2_x = np.sum(right[:,0]) # points 42 to 47 => 'x'
    asum2_y = np.sum(left[:,0])  # points 36 to 41 => 'x'
    
    denominador = asum2_x - asum2_y
    
    # compute angle=arctan(x)
    angle = np.degrees(np.arctan(numerador / denominador))
    
    ########################################
    ########################################
    ########################################
    #sum_x = sum([cord[1] for cord in right])
    #sum_y = sum([cord[1] for cord in left])
    
    #numerador = sum_x - sum_y
    
    #sum2_x = sum([cord[0] for cord in right])
    #sum2_y = sum([cord[0] for cord in left])
    
    #denominador = sum2_x - sum2_y
    
    #angle = math.atan(numerador / denominador)
    
    return angle


# angle2 = -0.05992815512120788 original

In [73]:
compute_angle(points)

-3.433630362450522

In [74]:
compute_distance(points)

83.33333333333333

In [85]:
from PIL import Image, ImageDraw


im = Image.open("C:/Users/virus/source/repos/DATASETS/PRUEBA/landmarck/rotate1.png").convert('RGB')
draw = ImageDraw.Draw(im)

draw.point(points_68, fill='red')

im.show()

In [81]:
# import the Python Image processing Library
from PIL import Image

# Create an Image object from an Image
colorImage  = Image.open("C:/Users/virus/source/repos/DATASETS/PRUEBA/landmarck/rotate1.png")
 
# Rotate it by 45 degrees
rotated = colorImage.rotate(3.433630362450522)

# Display the Original Image
#colorImage.show()

####rotated.convert('L').save("C:/Users/virus/source/repos/DATASETS/PRUEBA/landmarck/rotate11.png")
# Display the Image rotated by 45 degrees

rotated.show()

In [41]:
np.degrees(-0.05992815512120788)

-3.433630362450522

In [76]:
rotated = [(201, 228),
           (211, 222),
           (223, 223),
           (235, 230),
           (223, 233),
           (210, 233),
           (281, 230),
           (294, 223),
           (306, 223),
           (317, 228),
           (307, 233),
           (294, 233)]

In [77]:
compute_angle(rotated)

0.11551552798742593

In [75]:
compute_distance(rotated)

82.66666666666667

In [80]:
np.arctan(0)

0.0